model:
  name: xgboost

study:
  name: xgboost-optimisation
  storage: sqlite:///optuna.db

params:
  n_estimators: 300
  learning_rate: 0.05
  max_depth: 6
  min_child_weight: 1
  subsample: 1.0
  colsample_bytree: 1.0
  gamma: 0.0
  reg_alpha: 0.0
  reg_lambda: 1.0

optuna:
  enabled: true

  search_space:
    n_estimators:
      type: int
      low: 100
      high: 1000

    learning_rate:
      type: float
      low: 0.001
      high: 0.3
      log: true

    max_depth:
      type: int
      low: 3
      high: 12

    min_child_weight:
      type: int
      low: 1
      high: 10

    subsample:
      type: float
      low: 0.5
      high: 1.0

    colsample_bytree:
      type: float
      low: 0.5
      high: 1.0

    gamma:
      type: float
      low: 0.0
      high: 5.0

    reg_alpha:
      type: float
      low: 0.0
      high: 10.0

    reg_lambda:
      type: float
      low: 0.0
      high: 10.0
