tracking:
  uri: sqlite:///mlflow.db

data:
  path: data/train.csv
  target: target

features:
  numeric:
    - feature_1
    - feature_2
    - feature_3
    - feature_gaussian
    - feature_lognormal
    - feature_exponential

  categorical:
    - category
    - type

random_state: 42

model:
  name: random_forest

params:
  n_estimators: 200
  max_depth: 10
  min_samples_split: 2

study:
  name: random_forest-optimisation
  storage: sqlite:///optuna.db

optuna:
  metric: rmse
  n_trials: 100
  n_jobs: 6

  search_space:
    n_estimators:
      type: int
      low: 50
      high: 500

    max_depth:
      type: int
      low: 2
      high: 30

    min_samples_split:
      type: int
      low: 2
      high: 20
