tracking:
  uri: sqlite:///mlflow.db

data:
  path: data/train.csv
  target: target

features:
  numeric:
    - feature_1
    - feature_2
    - feature_3
    - feature_gaussian
    - feature_lognormal
    - feature_exponential

  categorical:
    - category
    - type

random_state: 42

model:
  name: xgboost

params:
  colsample_bytree: 0.96
  min_child_weight: 9
  reg_alpha: 4.485
  max_depth: 3
  subsample: 0.565
  learning_rate: 0.045
  n_estimators: 962
  gamma: 0
  reg_lambda: 0.014

save_name_suffix: best

study:

optuna:
  metric: mae
